# source: https://github.com/TRIGONIM/lua-requests-async/blob/main/.github/workflows/release.yml
name: "release"
on:
  push:
    tags:
      - 'v*'
jobs:
  luarocks-upload:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: LuaRocks Upload
        uses: nvim-neorocks/luarocks-tag-release@v4
        env:
          LUAROCKS_API_KEY: ${{ secrets.LUAROCKS_API_KEY }}
        with:
          summary: "Functions from Garry's Mod for standalone Lua."
          detailed_description: |
            A set of functions and libraries from Garry's Mod,
            such as http.*, timer.*, MsgC, PrintTable, string, table, etc.,
            for quickly creating applications using pure Lua (outside the game).
            More info: https://github.com/TRIGONIM/lua-gmod-lib/
          dependencies: |
            copas >= 4.3.0
            lua-requests-async
          labels: |
            copas
            requests
            http
            garrysmod
            timer
            PrintTable
            utils
            plenary
          # copy_directories: |
          #   dir
